Update Sync.yml

diff --git a/.github/workflows/Sync.yml b/.github/workflows/Sync.yml
--- a/.github/workflows/Sync.yml
+++ b/.github/workflows/Sync.yml
@@ -1,19 +1,34 @@
-name: Sync Fork
+name: Upstream Sync
+
+permissions:
+    contents: write
 
 on:
-  schedule:
-    - cron: '* */24 * * *' # 每天一次
-  workflow_dispatch: # on button click
+    schedule:
+        - cron: "0 0 * * *"
+    workflow_dispatch:
 
 jobs:
-  sync:
+    sync_with_upstream:
+        name: Sync with Upstream
+        runs-on: ubuntu-latest
+        if: ${{ github.event.repository.fork }}
 
-    runs-on: ubuntu-latest
+        steps:
+            - name: Checkout target repo
+              uses: actions/checkout@v3
 
-    steps:
-      - uses: tgymnich/fork-sync@v1.8
-        with:
-          token: ${{ secrets.PERSONAL_TOKEN }}
-          owner: mack-a
-          base: master
-          head: master
+            - name: Sync Upstream
+              uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
+              with:
+                  target_repo_token: ${{ secrets.GITHUB_TOKEN }}
+                  upstream_sync_repo: HackJava/HackJava
+                  upstream_sync_branch: main
+                  target_sync_branch: main
+                  test_mode: false
+
+            - name: Check for Failure
+              if: failure()
+              run: |
+                  echo "[Error] Due to a change in the workflow file of the upstream repository, GitHub has automatically suspended the scheduled automatic update. You need to manually sync your fork."
+                  exit 1
